version: "3.6"
services:
  web:
    image: nginx:latest
    container_name: intronet-front-debug
    volumes:
      - ./build:/app
      - ./public/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80

