version: "3.6"
services:
  web:
    build:
      context: .
    image: "${IMAGE_NAME}:${GITHUB_SHA}"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: intronet-front
    ports:
      - "4000:80"
    networks:
      apps:
    links:
      - db
    depends_on:
      - db

  db:
    container_name: insomnia_couchdb
    image: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
    networks:
      apps:
    volumes:
      - ./.data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.ini

networks:
  apps:
    external: true
