version: "3.8"
name: intronet-local
services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../dist/bundle:/app
      - ../../public:/app/public:ro
    ports:
      - 5002:80
    links:
      - server
      - mongo-express
    depends_on:
      - server
      - mongo-express
    networks:
      main:
    restart: always

  server:
    image: node:18-alpine
    volumes:
      - ../../server/dist/esm:/app
      - ../../server/node_modules:/node_modules:ro
      - ./secrets:/secrets
    command: "node /app/index.js"
    environment:
      PORT: "80"
      DATABASE: "mongodb://mongodb:27017"
      MONGODB_USER: admin
      MONGODB_PASSWORD: password
    ports:
      - 5003:80
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      main:
    restart: always

  mongodb:
    image: mongo:7.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./.data:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      main:

  mongo-express:
    image: mongo-express:1.0.0-18-alpine3.18
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "password"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - main
    depends_on:
      - mongodb

networks:
  main:
    driver: bridge
