version: "3.8"
name: intronet-local
services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../dist/bundle:/app
      - ../../public:/app/public:ro
    ports:
      - 5002:80
    links:
      - server
    depends_on:
      - server
    networks:
      main:

  server:
    image: node:18-alpine
    volumes:
      - ../../server/dist/esm:/app
      - ../../node_modules:/node_modules:ro
      - ./secrets:/secrets
    command: "node /app/index.js"
    environment:
      PORT: "80"
      DATABASE: "http://couchdb:5984"
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - 5003:80
    links:
      - couchdb
    depends_on:
      - couchdb
    networks:
      main:

  couchdb:
    image: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - ./.data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.ini
    ports:
      - "5984:5984"
    networks:
      main:

networks:
  main:
    driver: bridge
