version: "3.8"
name: intronet-local
services:
  web:
    image: nginx:latest
    hostname: insight-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../web/dist/bundle:/app/dist:ro
      - ../../web/public:/app/public:ro
    ports:
      - 5002:80
    expose:
      - 80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - server
      - mongo-express
    depends_on:
      - server
      - mongo-express
    networks:
      main:
      host_local:
    restart: always

  server:
    image: node:20-alpine
    volumes:
      - ../../server/dist/esm:/app/dist
      - ../../node_modules:/node_modules:ro
      - ../../server/node_modules:/app/node_modules:ro
      - ./secrets:/secrets
    command: "node /app/dist/index.js"
    env_file:
      - ../../server/.env.local
    environment:
      PORT: "80"
      DATABASE: "mongodb://mongodb:27017"
      MONGODB_USER: admin
      MONGODB_PASSWORD: password
    ports:
      - 5003:80
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      main:
    restart: always

  mongodb:
    image: mongo:7.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./.data:/data/db
    restart: always
    ports:
      - "27017:27017"
    networks:
      main:

  mongo-express:
    image: mongo-express:1.0.0-18-alpine3.18
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "password"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "5004:8081"
    networks:
      - main
    depends_on:
      - mongodb
    restart: always

networks:
  main:
    driver: bridge
  host_local:
    driver: bridge
