version: "3.8"

name: intronet-prod
services:
  nginx:
    image: "ghcr.io/insomnia-it/nginx:GITHUB_SHA"
    build:
      context: ../nginx
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      apps:
    links:
      - front
      - dbui
      - server
    depends_on:
      - front
      - dbui
      - server


  front:
    image: "ghcr.io/insomnia-it/front:GITHUB_SHA"
    build:
      context: ../../
      dockerfile: .deploy/client.Dockerfile
    restart: always
    networks:
      apps:

  server:
    image: "ghcr.io/insomnia-it/server:GITHUB_SHA"
    build:
      context: ../../
      dockerfile: .deploy/server.Dockerfile
    environment:
      PORT: "80"
      DATABASE: "mongodb://db:27017"
      MONGODB_USER: "admin"
      MONGODB_PASSWORD: "${DB_PASSWORD}"
    restart: always
    volumes:
      - "${WEBAPP_STORAGE_HOME}/secrets:/web/secrets"
    links:
      - db
    depends_on:
      - db
    networks:
      apps:

  db:
    image: mongo:7.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "${WEBAPP_STORAGE_HOME}/data:/data/db"
    restart: always
    networks:
      apps:

  dbui:
    image: mongo-express:1.0.0-18-alpine3.18
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "${DB_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "db"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_SITE_BASEURL: "/db/"
    ports:
      - "8081:8081"
    networks:
      - apps
    depends_on:
      - db

volumes:
  couchdb_data:

networks:
  apps:
    driver: bridge
