version: "3.8"

name: intronet-prod
services:
  nginx:
    image: "ghcr.io/insomnia-it/nginx:GITHUB_SHA"
    build:
      context: ../../nginx
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - "8081:80"
    networks:
      apps:
    links:
      - front
      - db
      - server
    depends_on:
      - front
      - db
      - server


  front:
    image: "ghcr.io/insomnia-it/front:GITHUB_SHA"
    build:
      context: ../../
      dockerfile: .deploy/client.Dockerfile
    restart: always
    networks:
      apps:

  server:
    image: "ghcr.io/insomnia-it/server:GITHUB_SHA"
    build:
      context: ../../
      dockerfile: .deploy/server.Dockerfile
    environment:
      PORT: "80"
      DATABASE: "http://admin:${DB_PASSWORD}@db:5984"
    restart: always
    volumes:
      - "${WEBAPP_STORAGE_HOME}/secrets:/app/secrets"
    links:
      - db
    depends_on:
      - db
    networks:
      apps:

  db:
    image: "ghcr.io/insomnia-it/db:GITHUB_SHA"
    build:
      context: ../couchdb
      dockerfile: db.Dockerfile
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: "${DB_PASSWORD}"
    restart: always
    networks:
      apps:
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:

networks:
  apps:
    driver: bridge
