name: Docker Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: subsitutte GITHUB_SHA in docker
        working-directory: ./.deploy/prod
        run: |
          sed -i s/GITHUB_SHA/${GITHUB_SHA}/g ./docker-compose.yml
          sed -i s/GITHUB_SHA/${GITHUB_SHA}/g ./kubernates.yaml
          cat ./docker-compose.yml

      - name: build docker
        working-directory: ./.deploy/prod
        run: docker compose build

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push docker
        working-directory: ./.deploy/prod
        run: docker compose push

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Gets K8s context
        uses: azure/k8s-set-context@v3
        with:
          method: service-principal
          cluster-type: arc
          resource-group: Insight
          cluster-name: InsightKube
        id: login

      - name: Deploys application
        uses: Azure/k8s-deploy@dd4bbd13a5abd2fc9ca8bdcb8aee152bb718fa78
        with:
          manifests: .deploy/prod/kubernates.yaml
          action: deploy
