name: Docker Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: subsitutte GITHUB_SHA in docker
        working-directory: ./.deploy/prod
        run: |
          sed -i s/GITHUB_SHA/${GITHUB_SHA}/g ./docker-compose.yml
          cat ./docker-compose.yml

      - name: build docker
        working-directory: ./.deploy/prod
        run: docker compose build

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push docker
        working-directory: ./.deploy/prod
        run: docker compose push

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp compose create \
              -g Insight \
              --environment InsightApp \
              --compose-file-path ".deploy/prod/docker-compose.yml"
