name: Docker Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: subsitutte GITHUB_SHA in docker
        working-directory: ./.deploy/prod
        run: |
          sed -i s/GITHUB_SHA/${{ env.GITHUB_SHA }}/g ./docker-compose.yml
          cat ./docker-compose.yml

      - name: build and push docker
        working-directory: ./.deploy/prod
        run: |
          docker compose build
          docker login ghcr.io -u franzzua -p ${{ secrets.DOCKER_TOKEN }}
          docker compose push

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp config container set --resource-group Insight --name insight-app --multicontainer-config-type compose --multicontainer-config-file ./.deploy/prod/docker-compose.yml
