name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: [self-hosted, acsrv]
    env:
      IMAGE_NAME: intronet-front
      IMAGE_NAME_SERVER: intronet-server
    steps:
      - uses: actions/checkout@v3
      - name: Build and run docker
        run: |
          docker build . --tag $IMAGE_NAME:$GITHUB_SHA
          docker build server --tag $IMAGE_NAME_SERVER:$GITHUB_SHA
          docker-compose down
          docker-compose up -d --no-build
          docker container prune --filter "until=24h" -f
          docker image prune -a -f --filter "until=24h"
