name: Docker Build

on:
  push:
    branches:
      - 'master'

env:
  CLUSTER_NAME: InsightKube
  CLUSTER_RESOURCE_GROUP: Insight
  DEPLOYMENT_MANIFEST_PATH: |
    ./.deploy/prod/kubernetes.yaml
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: substitute GITHUB_SHA in docker
        working-directory: ./.deploy/prod
        run: |
          sed -i s/GITHUB_SHA/${GITHUB_SHA}/g ./docker-compose.yml

      - name: build docker
        working-directory: ./.deploy/prod
        run: docker compose build

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push docker
        working-directory: ./.deploy/prod
        run: docker compose push

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - name: substitute GITHUB_SHA in kubernetes
        working-directory: ./.deploy/prod
        run: |
          sed -i s/GITHUB_SHA/${GITHUB_SHA}/g ./kubernetes.yaml
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: azure/use-kubelogin@v1
        name: Set up kubelogin for non-interactive login
        with:
          kubelogin-version: v0.0.25
      - uses: azure/aks-set-context@v3
        name: Get K8s context
        with:
          admin: "false"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          use-kubelogin: "true"

      - name: "Create deployment"
        uses: okteto/apply@master
        with:
          manifest: ${{ env.DEPLOYMENT_MANIFEST_PATH }}


